#pragma once


#define SDMMC_CLK_GPIO GPIO_NUM_2
#define SDMMC_CMD_GPIO GPIO_NUM_6
#define SDMMC_DATA0_GPIO GPIO_NUM_16
#define SDMMC_DATA1_GPIO GPIO_NUM_17
#define SDMMC_DATA2_GPIO GPIO_NUM_4
#define SDMMC_DATA3_GPIO GPIO_NUM_5
#define SD_DET_PIN GPIO_NUM_18
#define sdcard_mount_point "/sdcard"


/*
触摸传感器通道 GPIO 管脚
T0 GPIO4
T1 GPIO0
T2 GPIO2
T3 MTDO GPIO15
T4 MTCK GPIO13
T5 MTDI GPIO12
T6 MTMS GPIO14
T7 GPIO27
T8 2K_XN
T9 2K_XP*/
#define TOUCH_PAD_NUM GPIO_NUM_14

#define LED_STRIP_GPIO_PIN  48
#define LED_STRIP_LED_COUNT 1